steps:
- id: 'go-get'
  name: 'gcr.io/cloud-builders/go'
  entrypoint: go
  args:
    - get
    - -t
    - -v 
    - ./...

- id: 'test'
  name: 'gcr.io/cloud-builders/go'
  entrypoint: '/bin/sh'
  env:
    - CGO_ENABLED=1
    - GOOS=linux
    - GOARCH=amd64
    - GOPRIVATE=github.com/lytics
    - GOBIN=/workspace/gobin
  args:
    - go.test.sh
  waitFor: ['go-get']
