ignore:
  # - "**/*.pb.go" # ignore protobuf files
  - "schema/schema.pb.go"
  - "examples/**/*"
  - "datasource/mockcsvtestdata/*"
  - "dialects/**/*"
  - "generators/**/*"
  - "generators/*"
  - "testutil/*"